from enum import Enum

from pyodmv2.utils.forest import Forest

class OdmV2(Enum):
    ODM = "ODM"
    StudyEventData = "StudyEventData"
    SiteRef = "SiteRef"
    InvestigatorRef = "InvestigatorRef"
    StudyEventRepeatKey = "StudyEventRepeatKey"
    Association = "Association"
    AdminData = "AdminData"
    Study = "Study"
    ReferenceData = "ReferenceData"
    Description = "Description"
    CreationDateTime = "CreationDateTime"
    Originator = "Originator"
    FileOID = "FileOID"
    ODMVersion = "ODMVersion"
    Context = "Context"
    AsOfDateTime = "AsOfDateTime"
    SourceSystemVersion = "SourceSystemVersion"
    Granularity = "Granularity"
    SourceSystem = "SourceSystem"
    PriorFileOID = "PriorFileOID"
    FileType = "FileType"
    ItemGroupRepeatKey = "ItemGroupRepeatKey"
    ItemData = "ItemData"
    Value = "Value"
    SubjectKey = "SubjectKey"
    SeqNum = "SeqNum"
    ItemOID = "ItemOID"
    ItemGroupDataSeq = "ItemGroupDataSeq"
    ItemGroupOID = "ItemGroupOID"
    StudyEventOID = "StudyEventOID"
    StudyOID = "StudyOID"
    MetaDataVersionOID = "MetaDataVersionOID"
    SubjectData = "SubjectData"
    ItemGroupData = "ItemGroupData"
    AuditRecord = "AuditRecord"
    Signature = "Signature"
    Annotation = "Annotation"
    Query = "Query"
    ClinicalData = "ClinicalData"
    TransactionType = "TransactionType"
    IsNull = "IsNull"
